// Generated by CoffeeScript 2.7.0
export var echo = console.log;

export var range = _.range;

export var global = {
  settings: {
    TITLE: 'Titel saknas',
    GAMES: 1,
    ROUNDS: 0,
    SORT: 1,
    ONE: 1,
    BALANCE: 1,
    DECIMALS: 3,
    A: 30,
    B: 30,
    C: 30 // ONE = 1 # 0=dev 1=prod
  },
  players: [],
  player: null,
  results: [], // ronder x bord. cell: 'x', '0', '1' eller '2'
  rounds: [], // ronder x bord. cell: [w,b] 
  longs: [], // players x ronder. cell: [w,b,col,res]
  currScreen: 'a',
  currRound: 0,
  currTable: 0,
  sortKey: '#',
  frirond: null, // ingen frirond. Annars index för frironden
  berger: null,
  floating: null
};

//translator : null

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiZ2xvYmFsLmpzIiwic291cmNlUm9vdCI6IlxcIiwic291cmNlcyI6WyJnbG9iYWwuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxPQUFBLElBQU8sSUFBQSxHQUFPLE9BQU8sQ0FBQzs7QUFDdEIsT0FBQSxJQUFPLEtBQUEsR0FBUSxDQUFDLENBQUM7O0FBRWpCLE9BQUEsSUFBTyxNQUFBLEdBQVM7RUFDZixRQUFBLEVBQVc7SUFBQyxLQUFBLEVBQU0sY0FBUDtJQUF1QixLQUFBLEVBQU0sQ0FBN0I7SUFBZ0MsTUFBQSxFQUFPLENBQXZDO0lBQTBDLElBQUEsRUFBSyxDQUEvQztJQUFrRCxHQUFBLEVBQUksQ0FBdEQ7SUFBeUQsT0FBQSxFQUFRLENBQWpFO0lBQW9FLFFBQUEsRUFBUyxDQUE3RTtJQUFnRixDQUFBLEVBQUUsRUFBbEY7SUFBc0YsQ0FBQSxFQUFFLEVBQXhGO0lBQTRGLENBQUEsRUFBRSxFQUE5RjtFQUFBLENBREk7RUFHZixPQUFBLEVBQVUsRUFISztFQUlmLE1BQUEsRUFBUyxJQUpNO0VBTWYsT0FBQSxFQUFVLEVBTks7RUFPZixNQUFBLEVBQVUsRUFQSztFQVFmLEtBQUEsRUFBVSxFQVJLO0VBVWYsVUFBQSxFQUFhLEdBVkU7RUFXZixTQUFBLEVBQVksQ0FYRztFQVlmLFNBQUEsRUFBWSxDQVpHO0VBY2YsT0FBQSxFQUFVLEdBZEs7RUFnQmYsT0FBQSxFQUFVLElBaEJLO0VBa0JmLE1BQUEsRUFBUyxJQWxCTTtFQW1CZixRQUFBLEVBQVc7QUFuQkk7O0FBSGhCIiwic291cmNlc0NvbnRlbnQiOlsiZXhwb3J0IGVjaG8gPSBjb25zb2xlLmxvZ1xyXG5leHBvcnQgcmFuZ2UgPSBfLnJhbmdlXHJcblxyXG5leHBvcnQgZ2xvYmFsID0ge1xyXG5cdHNldHRpbmdzIDoge1RJVExFOidUaXRlbCBzYWtuYXMnLCBHQU1FUzoxLCBST1VORFM6MCwgU09SVDoxLCBPTkU6MSwgQkFMQU5DRToxLCBERUNJTUFMUzozLCBBOjMwLCBCOjMwLCBDOjMwfSAjIE9ORSA9IDEgIyAwPWRldiAxPXByb2RcclxuXHJcblx0cGxheWVycyA6IFtdXHJcblx0cGxheWVyIDogbnVsbFxyXG5cclxuXHRyZXN1bHRzIDogW10gIyByb25kZXIgeCBib3JkLiBjZWxsOiAneCcsICcwJywgJzEnIGVsbGVyICcyJ1xyXG5cdHJvdW5kcyAgOiBbXSAjIHJvbmRlciB4IGJvcmQuIGNlbGw6IFt3LGJdIFxyXG5cdGxvbmdzICAgOiBbXSAjIHBsYXllcnMgeCByb25kZXIuIGNlbGw6IFt3LGIsY29sLHJlc11cclxuXHJcblx0Y3VyclNjcmVlbiA6ICdhJ1xyXG5cdGN1cnJSb3VuZCA6IDBcclxuXHRjdXJyVGFibGUgOiAwXHJcblxyXG5cdHNvcnRLZXkgOiAnIydcclxuXHJcblx0ZnJpcm9uZCA6IG51bGwgIyBpbmdlbiBmcmlyb25kLiBBbm5hcnMgaW5kZXggZsO2ciBmcmlyb25kZW5cclxuXHJcblx0YmVyZ2VyIDogbnVsbFxyXG5cdGZsb2F0aW5nIDogbnVsbFxyXG5cdCN0cmFuc2xhdG9yIDogbnVsbFxyXG59Il19
//# sourceURL=c:\github\FloatingBerger\global.coffee