// Generated by CoffeeScript 2.7.0
export var Player = class Player {
  constructor(id, name, elo) {
    this.id = id;
    this.name = name;
    this.elo = elo;
    this.opp = []; // används endast av Floating
    this.col = ""; // används endast av Floating
  }

  balans() {
    var b, c, i, len, ref;
    b = 0;
    ref = this.col;
    for (i = 0, len = ref.length; i < len; i++) {
      c = ref[i];
      if (c === 'w') {
        b++;
      }
      if (c === 'b') {
        b--;
      }
    }
    return b;
  }

  toString() {
    return `${String(this.elo).padStart(4, '0')} ${this.name}`;
  }

};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGxheWVyLmpzIiwic291cmNlUm9vdCI6IlxcIiwic291cmNlcyI6WyJwbGF5ZXIuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxPQUFBLElBQWEsU0FBTixNQUFBLE9BQUE7RUFDTixXQUFjLEdBQUEsTUFBQSxLQUFBLENBQUE7SUFBQyxJQUFDLENBQUE7SUFBSSxJQUFDLENBQUE7SUFBTSxJQUFDLENBQUE7SUFDM0IsSUFBQyxDQUFBLEdBQUQsR0FBTyxHQUFUO0lBQ0UsSUFBQyxDQUFBLEdBQUQsR0FBTyxHQUZNO0VBQUE7O0VBR2QsTUFBUyxDQUFBLENBQUE7QUFDVixRQUFBLENBQUEsRUFBQSxDQUFBLEVBQUEsQ0FBQSxFQUFBLEdBQUEsRUFBQTtJQUFFLENBQUEsR0FBSTtBQUNKO0lBQUEsS0FBQSxxQ0FBQTs7TUFDQyxJQUFHLENBQUEsS0FBRyxHQUFOO1FBQWUsQ0FBQSxHQUFmOztNQUNBLElBQUcsQ0FBQSxLQUFHLEdBQU47UUFBZSxDQUFBLEdBQWY7O0lBRkQ7V0FHQTtFQUxROztFQU9ULFFBQVUsQ0FBQSxDQUFBO1dBQUcsQ0FBQSxDQUFBLENBQUcsTUFBQSxDQUFPLElBQUMsQ0FBQSxHQUFSLENBQVksQ0FBQyxRQUFiLENBQXNCLENBQXRCLEVBQXlCLEdBQXpCLENBQUgsRUFBQSxDQUFBLENBQW1DLElBQUMsQ0FBQSxJQUFwQyxDQUFBO0VBQUg7O0FBWEoiLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnQgY2xhc3MgUGxheWVyXHJcblx0Y29uc3RydWN0b3IgOiAoQGlkLCBAbmFtZSwgQGVsbykgLT5cclxuXHRcdEBvcHAgPSBbXSAjIGFudsOkbmRzIGVuZGFzdCBhdiBGbG9hdGluZ1xyXG5cdFx0QGNvbCA9IFwiXCIgIyBhbnbDpG5kcyBlbmRhc3QgYXYgRmxvYXRpbmdcclxuXHRiYWxhbnMgOiAtPlxyXG5cdFx0YiA9IDBcclxuXHRcdGZvciBjIGluIEBjb2xcclxuXHRcdFx0aWYgYz09J3cnIHRoZW4gYisrXHJcblx0XHRcdGlmIGM9PSdiJyB0aGVuIGItLVxyXG5cdFx0YlxyXG5cclxuXHR0b1N0cmluZzogLT4gXCIje1N0cmluZyhAZWxvKS5wYWRTdGFydCA0LCAnMCd9ICN7QG5hbWV9XCJcclxuIl19
//# sourceURL=c:\github\2025\013-FloatingBerger\player.coffee